---
title: "Aggregate Results"
author: "Yvonne Barkley"
date: "August 30, 2018"
output: html_notebook
---

Use aggregate function to complete various analyses of the test results.

```{r}
# This code aggregates the classification results of the test data from the different iterations of Random Forests to  

library(plyr)
library(reshape2)


today = 20190325
model = 'PN'
thld = 50  # Equates to a threshold of the number of whistles that must be correctly classified to classify the encounter to the correct population. 
# For example, 50 is 33% of 150 whistles, then 75 is 50% for pairwise classifiers.

####Load Data####
# Load acoustic encounter csv
agg_data <- read.csv('data/results/PcResults_PMN_EncounterClass_20190322.csv')

agg_data <- read.csv('data/results/PcResults_PM_EncounterClass_20190325.csv')

agg_data <- read.csv('data/results/PcResults_PN_EncounterClass_20190325.csv')
```




```{r}

agg_data<-agg_data[order(agg_data$EncounterID),]
# YB 3/22/19
####with new majority vote classificaiton ####

#Get number of times each encounter was included in the test data

IDs <- unique(agg_data$EncounterID)
pc_sum = NULL
pc_encID = NULL

for (k in 1:length(IDs)){
  temp <- agg_data[agg_data$EncounterID==IDs[k], ] #subset by encounter
  # does the classification match the population? If yes, give it the population name (level number). If no, give it a zero.
  pc_pred <-ifelse(temp$population == temp$classification, unique(temp$population),  ifelse(temp$population != temp$classification, 0, NA))
  
  pc_sum[k] <- sum(pc_pred != 0) #sum total the does not equal zero.
  pc_encID = rbind(pc_encID, unique(levels(temp$EncounterID))[k]) #pull out each EncID into a new column for each iteration. 
  }
pc_total = cbind.data.frame(pc_encID, pc_sum)  #total  number of correct class by majority per encounter

agg_temp <- aggregate(population~EncounterID, agg_data, length) #get total frequency of encounters included in all iterations

#Combine everything and calculate percentage true
agg_total <- cbind.data.frame('EncounterID'=agg_temp[,1], 
                              'observed'=agg_temp[,2], 
                              'predicted'=pc_total[,2], 
                              'percentage true'=pc_total$pc_sum/agg_temp$population*100)

fn1 = sprintf("%s", model)
fn2 = sprintf("%s.csv", today)
write.csv(agg_total, file= paste('PcResults_', fn1, '_AggregatedTestResults_MajorityVote_', fn2, sep=""), row.names = F )



```


#WRONG
```{r}

#Import PcResults_TestResults csv for the classifier
agg_data <- read.csv('data/PcResults_TestResults_PMN_20181209.csv')


#1. How many times was each acoustic encounter represented in the test data?
AcEncs_Test <- aggregate(x = agg_data, 
                               by = list(unique.values = agg_data$EncounterID),                                FUN = length)

#2. Loop the subsetting to sum up the number of times the number of correctly classified whistles exceeded the threshold for each acoustic encounter.

IDs <- unique(agg_data$EncounterID)
filtByEnc = NULL
filtCorrect = NULL
for (k in 1:length(IDs)){
  temp <- agg_data[agg_data$EncounterID==IDs[k], ]
  correct <- data.frame("EncounterID" = IDs[k], "agg_x"=sum(temp$CorrectDW > thld)) # sum up the number of times the correct whistle classifications exceeded the threshold for each encounter
  filtCorrect = rbind(filtCorrect, correct)
  filtByEnc = rbind(filtByEnc, temp)
}
filtCorrect$EncounterID <-as.character(filtCorrect$EncounterID) 

filtCorrect <- filtCorrect[order(as.character(filtCorrect$EncounterID)),]

#What is the number of correctly classified encounters based on the number of times the acoustic encounter was included in the test data?
#Combine filtered correct data with tally of times ac enc was included in the test data
agg_data_sum <- cbind(filtCorrect, "agg_y" = AcEncs_Test$rep)

#Divide columns to get proportional data and add that into a third column
#library(dplyr)
agg_data_sum <- mutate(agg_data_sum, new = agg_x/agg_y)

fn = sprintf("%s_%s_%s.csv", thld, model, today)
write.csv(agg_data_sum, file= paste('PcResults_AggregatedTestResults_MajorityVote_thld', fn, sep=""), row.names = F )
#write.csv(filtByEnc,'C:\\Users\\Yvonne\\OneDrive\\PHD\\CHP1-FKW\\data\\results\\2018\\PcResults_OrderedTestResults_PM_20180830.csv', row.names = F )
```

##ANOVA Action
```{r}


require(dplyr)
require(tidyverse)

#Format agg_x so each population represents a column with group
agg_data$population[agg_data$EncounterID == "M2"]='MHI'
agg_data$population[agg_data$EncounterID ==  "M3"]='MHI'
agg_data$population[agg_data$EncounterID ==  "M4"]='MHI'
agg_data$population[agg_data$EncounterID ==  "M1"]='MHI'
agg_data$population[agg_data$EncounterID ==  "P6"]='Pelagic'
agg_data$population[agg_data$EncounterID ==  "P1"]='Pelagic'
agg_data$population[agg_data$EncounterID ==  "P2"]='Pelagic'
agg_data$population[agg_data$EncounterID ==  "P4"]='Pelagic'
agg_data$population[agg_data$EncounterID ==  "P5"]='Pelagic'
agg_data$population[agg_data$EncounterID ==  "P3"]='Pelagic'
agg_data$population[agg_data$EncounterID ==  "P8"]='Pelagic'
agg_data$population[agg_data$EncounterID ==  "P7"]='Pelagic'
agg_data$population[agg_data$EncounterID ==  "N2"]='NWHI'
agg_data$population[agg_data$EncounterID ==  "N3"]='NWHI'
agg_data$population[agg_data$EncounterID ==  "N4"]='NWHI'
agg_data$population[agg_data$EncounterID ==  "N1"]='NWHI'
agg_data$population <- as.factor(agg_data$population)

agg_sub <- agg_data %>% filter(CorrectDW > thld) #| CorrectDW < 80)  #Outliers exist past 80 DW


agg_sub <- agg_sub[, c(3,8,9)]

m=filter(agg_sub, population=='MHI')
p=filter(agg_sub, population=='Pelagic')
n=filter(agg_sub, population=='NWHI')

#Levene's Test of equal variances
library(car)
leveneTest(log(n$CorrectDW), n$EncounterID, data=agg_sub) #Null: variances are equal
shapiro.test(log(agg_data$CorrectDW)) #Null: Sample distribution is normal.
qqPlot(log(p$CorrectDW))


#For unbalanced data between encounters (NOT dealing with unbalanced nested ANOVA)
m.model = lm(CorrectDW ~ EncounterID, 
           data=m)
Anova(m.model, type="II") 
hist(residuals(m.model), 
     col="darkgray")
plot(fitted(m.model), 
     residuals(m.model))

library(agricolae)
(HSD.test(m.model, "EncounterID"))

p.model = lm(CorrectDW ~ EncounterID, 
           data=p)
Anova(p.model, type="II") 
hist(residuals(p.model), 
     col="darkgray")
plot(fitted(p.model), 
     residuals(p.model))

(HSD.test(p.model, "EncounterID"))


n.model = lm(CorrectDW ~ EncounterID, 
           data=n)
Anova(n.model, type="II") 
hist(residuals(n.model), 
     col="darkgray")
plot(fitted(n.model), 
     residuals(n.model))

(HSD.test(n.model, "EncounterID"))






```




