---
title: "Importance Variable Plots"
output: html_notebook
---

This script plots the top 10 important variables factored by population and encounter. It is intended to explore the differences in values between the new whistles (sans HARP) and old whistles.
```{r warning=FALSE, message=FALSE}
library(ggplot2)
library(reshape2)
library(stringr)
library(dplyr)
```

#12/10/18
#Added method of extracting top 5 variables from each run

```{r}
#read in important variables spreadsheet

top_vars <- read.csv("C:\\Users\\yvers\\OneDrive\\PHD\\CHP1-FKW\\data\\results\\2018\\20181209_PMN_100x/PcResults_ImportantVars_PMN_20181209_EDIT.csv")
top_varsPN <- read.csv("C:\\Users\\yvers\\OneDrive\\PHD\\CHP1-FKW\\data\\results\\2018\\20180824_PN_100x/PcResults_ImportantVars_PN_20180824.csv")
top_varsPM <- read.csv("C:\\Users\\yvers\\OneDrive\\PHD\\CHP1-FKW\\data\\results\\2018\\20180822_PM_100x/PcResults_ImportantVars_PM_20180822_edit.csv")
#Using dplyr functions

top_vars$model <- 'RF_PNM'
top_varsPN$model <- 'RF_PN'
top_varsPM$model <- 'RF_PM'

top_5 <- droplevels(top_vars %>%
  group_by(Rep) %>%
  top_n(n = 5, wt = MeanDecreaseAccuracy))

top_5PN <- droplevels(top_varsPN %>%
  group_by(Rep) %>%
  top_n(n = 5, wt = MeanDecreaseAccuracy))

top_5PM <- droplevels(top_varsPM %>%
  group_by(Rep) %>%
  top_n(n = 5, wt = MeanDecreaseAccuracy))

top_5 <- top_5[,c(1,2,6)]
top_5PN <- top_5PN[, c(1,2,5)]
top_5PM <- top_5PM[, c(1,2,5)]

top_5$model <- 'RF_PNM'
top_5PN$model <- 'RF_PN'
top_5PM$model <- 'RF_PM'

top_5tab <- as.data.frame(sort(table(top_5$Variable)), decreasing = F)
top_5tabPN <- as.data.frame(sort(table(top_5PN$Variable)), decreasing = F)
top_5tabPM <- as.data.frame(sort(table(top_5PM$Variable)), decreasing = F)


top_5tab$model <- 'RF_PNM'
top_5tabPN$model <- 'RF_PN'
top_5tabPM$model <- 'RF_PM'

top_all< - rbind(top_5tab, top_5tabPN, top_5tabPM)
top_all$Variable <- as.character(top_5$Variable)


write.csv(top_5tab, "C:\\Users\\yvers\\OneDrive\\PHD\\CHP1-FKW\\data\\results\\2018\\20181209_PMN_100x/PcResults_Top5ImpVarsTABLE_PMN_20181209.csv", row.names = F)
write.csv(top_5tabPN, "C:\\Users\\yvers\\OneDrive\\PHD\\CHP1-FKW\\data\\results\\2018\\20181209_PMN_100x/PcResults_Top5ImpVarsTABLE_PN_20181209.csv", row.names = F)
write.csv(top_5tabPM, "C:\\Users\\yvers\\OneDrive\\PHD\\CHP1-FKW\\data\\results\\2018\\20181209_PMN_100x/PcResults_Top5ImpVarsTABLE_PM_20181209.csv", row.names = F)


top_5tab <- read.csv("C:\\Users\\yvers\\OneDrive\\PHD\\CHP1-FKW\\data\\results\\2018\\20181209_PMN_100x/PcResults_Top5ImpVarsTABLE_ALL_20181209.csv")

#Create a plot to visually represent table
#https://stackoverflow.com/questions/5804226/get-a-histogram-plot-of-factor-frequencies-summary
# require(lattice)
# with(top_5, dotplot(Variable, horizontal = FALSE))

require(ggplot2)
# make ROCCA.Variables an ordered factor

#top_5tab$Var1 <- factor(top_5tab$Var1, levels = top_5tab$Var1) #Only works with one model config
levels(top_5tab$model) <- c('RF_PNM', 'RF_PN', 'RF_PM')
pch = c(8, 17, 15)


p <- ggplot(top_5tab, aes(Var1, Freq)) + 
     geom_point(aes(pch=factor(model), size=2)) +
  
  labs(title="Important Variables in the Top 5 Ranking", x = "Whistle Variable", y= 'Frequency') + 
  theme_bw()+
  theme(plot.background = element_rect(fill = "white"),
        axis.text.x=element_text(size=12, angle = 90, hjust = 1), #5 for all encounters
        axis.text.y=element_text(size=12), #8 for all encounters
        plot.title=element_text(size=18, hjust=0.5, face="bold", colour="black", vjust=-1),
        legend.text = element_text(size=12),
        legend.title = element_text(size=14),
        legend.title.align = 0.5,
        axis.title = element_text(size=13, hjust=0.5))+
   #use inkscape to mask stupid size legend
  # scale_shape_manual(name='Model') +
  scale_shape_manual(values = c(8, 24, 22),
                     name='Model')
  #scale_color_discrete(name='Model') #only works for colored points
p 

ggsave('C:\\Users\\yvers\\OneDrive\\PHD\\CHP1-FKW\\data\\results\\2018\\plots/PcResults_Top5ImpVarsTABLE_ALL_20181209-new.png', width = 12, height = 8, units = "in", type = "cairo-png")  


```





#New Whistle Plots
```{r}

#shades of gray###
#color <- c('#35bb7c', 'black', '#947d51','#8576aa')

#new data
pcdata<-read.csv('C:\\Users\\Yvonne\\Documents\\PHD\\CHP1-FKW\\data\\2017- 100 New Whistles\\BigRoccaFile_PM_TowedAll.csv')

pcdata <- read.csv('C:\\Users\\Yvonne\\Documents\\PHD\\CHP1-FKW\\data/2017- 100 New Whistles\\ROCCA Towed Data\\BigRoccaFile_PMN_TowedAll_EDIT_20180816.csv')

pcdata.pm <- read.csv('C:\\Users\\Yvonne\\Documents\\PHD\\CHP1-FKW\\data/PcNWHI14-17_RoccaContourStats_20180813.csv')


#decimation test
pcdata<-read.csv('C:\\Users\\Yvonne\\Documents\\PHD\\CHP1-FKW\\data\\2017- 100 New Whistles/decimation_test/PcMHI31_32_RoccaContourStats_RAWDEC_edited.csv')


#subset for pelagic and mhi
pcdata <- subset(pcdata, pcdata$population != "nwhi")

#subset important variables
pcdata_sub <- pcdata[, c(1,3,7,8,14,15,31)]
pcdata_sub <- pcdata[, c(1, 3, 22, 30)] #22
pcdata_sub <- pcdata[, c(1, 3, 7)] #freqmax
pcdata_sub <- pcdata[, c(1, 3, 24)] #freqcofm




#remove Pel8
pcdata_sub <- subset(pcdata_sub, pcdata_sub$EncounterID != 'PcPEL8')

library('dplyr')
pcdata_sub %>% group_by(population) %>% summarize(median=median(FREQQUARTER3), sum=sum(FREQQUARTER3))

pcdata_sub %>% group_by(population) %>% summarize(median=median(FREQPOSSLOPEMEAN), sum=sum(FREQPOSSLOPEMEAN))

pcdata_sub %>% group_by(population) %>% summarize(mean=mean(FREQMAX), sum=sum(FREQMAX))

pcdata_sub %>% group_by(population) %>% summarize(mean=mean(FREQCOFM), sum=sum(FREQCOFM))
pcdata_sub %>% group_by(population) %>% summarize(mean=mean(FREQCOFM), median=median(FREQCOFM))


#decimation test
#pcdata_sub <- pcdata[, c(1,2,29,30)]

#Turn data into long format with melt()
#data_melt = melt(pcdata_sub, id.vars =c("population", "EncounterID"), measure.vars = c("DURATION", "FREQQUARTER3","FREQPOSSLOPEMEAN", "FREQNEGSLOPEMEAN", "FREQBEG" ))

#8/26/18
data_melt = melt(pcdata_sub, id.vars =c("population", "EncounterID"), measure.vars = c("FREQQUARTER3", "FREQPOSSLOPEMEAN")) 
data_melt = melt(pcdata_sub, id.vars =c("population", "EncounterID"), measure.vars = c("FREQPOSSLOPEMEAN"))#"",

#9/10/18
data_melt = melt(pcdata_sub, id.vars =c("population", "EncounterID"), measure.vars = c("FREQMAX"))#"",
data_melt = melt(pcdata_sub, id.vars =c("population", "EncounterID"), measure.vars = c("FREQCOFM"))


#decimation test
#data_melt = melt(pcdata_sub, id.vars =c("population", "EncounterID"), measure.vars = c("FREQPOSSLOPEMEAN", "FREQNEGSLOPEMEAN"))

#splitting up the EncounterID labels (PcPel1, PcPel2 etc) to make them Pel1, Pel2, to fit better on the plot axis 
data_melt$Encounter <-as.character(data_melt$EncounterID)
data_meltENC <- as.data.frame(str_split_fixed(data_melt$Encounter, "Pc", 2))
data_melt <- cbind(data_melt, data_meltENC)
data_melt_sub <- data_melt[, c(1,7,3,4)]  #reorder columns with new encounter name col
colnames(data_melt_sub)[2] <- "EncounterID" #rename new encounter name col

#Change variable names
data_melt_sub$variable = as.character(data_melt_sub$variable)
data_melt_sub$variable[data_melt_sub$variable == 'FREQQUARTER3'] = "Third Quarter Frequency"
data_melt_sub$variable[data_melt_sub$variable == 'FREQPOSSLOPEMEAN'] = "Mean Positive Slope Frequency"
data_melt_sub$variable[data_melt_sub$variable == 'FREQMAX'] = "Max Frequency"


data_melt_sub$variable = as.factor(data_melt_sub$variable)



data_melt_sub$population = as.character(data_melt_sub$population)
data_melt_sub$population[data_melt_sub$population == 'mhi'] = "MHI"
data_melt_sub$population[data_melt_sub$population == 'pel'] = "Pelagic"
data_melt_sub$population[data_melt_sub$population == 'nwhi'] = "NWHI"
data_melt_sub$population = as.factor(data_melt_sub$population)

data_melt_sub$EncounterID = as.character(data_melt_sub$EncounterID)
data_melt_sub$EncounterID[data_melt_sub$EncounterID == 'MHI31'] = "M2"
data_melt_sub$EncounterID[data_melt_sub$EncounterID == 'MHI32'] = "M3"
data_melt_sub$EncounterID[data_melt_sub$EncounterID == 'MHI33'] = "M4"
data_melt_sub$EncounterID[data_melt_sub$EncounterID == 'MHI34'] = "M1"
data_melt_sub$EncounterID[data_melt_sub$EncounterID == 'PEL1'] = "P6"
data_melt_sub$EncounterID[data_melt_sub$EncounterID == 'PEL2'] = "P1"
data_melt_sub$EncounterID[data_melt_sub$EncounterID == 'PEL3'] = "P2"
data_melt_sub$EncounterID[data_melt_sub$EncounterID == 'PEL4'] = "P4"
data_melt_sub$EncounterID[data_melt_sub$EncounterID == 'PEL5'] = "P5"
data_melt_sub$EncounterID[data_melt_sub$EncounterID == 'PEL6'] = "P3"
data_melt_sub$EncounterID[data_melt_sub$EncounterID == 'PEL7'] = "P8"
data_melt_sub$EncounterID[data_melt_sub$EncounterID == 'PEL8'] = "P7"
data_melt_sub$EncounterID[data_melt_sub$EncounterID == 'NWHI14'] = "N2"
data_melt_sub$EncounterID[data_melt_sub$EncounterID == 'NWHI15'] = "N3"
data_melt_sub$EncounterID[data_melt_sub$EncounterID == 'NWHI16'] = "N4"
data_melt_sub$EncounterID[data_melt_sub$EncounterID == 'NWHI17'] = "N1"
data_melt_sub$EncounterID = as.factor(data_melt_sub$EncounterID)




#change factor order
#reverse
data_melt_sub$population = with(data_melt_sub, factor(population, levels = rev(levels(population))))

data_melt_sub$variable = with(data_melt_sub, factor(variable, levels = rev(levels(variable))))

#custom
levels(data_melt_sub$EncounterID) <- c("P1", "P2", "P3", "P4", "P5", "P6", "P7", "P8", "N1", "N2", "N3", "N4", "M1", "M2", "M3", "M4" )

```

```{r}
#BY ENCOUNTER####
plot_enc<- ggplot(data_melt_sub, aes(y=value, x=EncounterID)) +  
  facet_wrap(~variable, scales = "free") +
  geom_boxplot(aes(colour=population)) +
  labs(title="Important ROCCA Variables by Encounter", subtitle="(Array Data Only)") + 
  theme(plot.background = element_rect(fill = "white"),
        axis.text.x=element_text(size=6), #5 for all encounters
        axis.text.y=element_text(size=10), #8 for all encounters
        plot.title=element_text(size=25, hjust=0.5, face="bold", colour="darkblue", vjust=-1),
        plot.subtitle=element_text(size=16, hjust=0.5, face="italic", color="black"))+
          guides(fill=guide_legend(title="Population"))
#saves plot with better resolution
ggsave('C:\\Users\\Yvonne\\Documents\\PHD\\CHP1-FKW\\data\\results\\20180717\\Pc_Boxplot_Encounters_array_20180717.png', width = 12, height = 8, units = "in", type = "cairo-png")  



##For decimation test
# plot_enc<- ggplot(data_melt_sub, aes(y=value, x=EncounterID)) +  
#   facet_wrap(~variable, scales = "free") +
#   geom_boxplot(aes(colour=population)) +
#   labs(title="Comparing slope values with different sampling freqs for PcMHI31 and PcMHI32", subtitle="(raw=500kHz, dec=192kHz)") + 
#   theme(plot.background = element_rect(fill = "white"),
#         axis.text.x=element_text(size=10), 
#         axis.text.y=element_text(size=10),
#         plot.title=element_text(size=20, hjust=0.5, face="bold", colour="darkblue", vjust=-1),
#         plot.subtitle=element_text(size=16, hjust=0.5, face="italic", color="black"))+
#           guides(fill=guide_legend(title="Population"))
# #save for decimation test plot
# ggsave('C:\\Users\\Yvonne\\Documents\\PHD\\CHP1-FKW\\data\\2017- 100 New Whistles/decimation_test/PcMHI31_32_Boxplot_decimation_20180702_1.png', width = 12, height = 8, units = "in", type = "cairo-png")  
```

9/7/2018
From Term Project in Intro to R, using facet_wrap
```{r}

#Plot variables by encounter
p<-ggplot(data_melt_sub,aes(y=value, x = population)) + 
  facet_wrap(~variable,scales = "free") + 
  geom_boxplot() +
  labs(title="Top Important Variables") +
  theme_bw()+
  theme(axis.text.x=element_text(size=12), 
        axis.title.x=element_text(size=14, face='bold'),
        axis.text.y=element_text(size=12), 
        axis.title.y=element_text(size=14, face='bold'),
         text=element_text(size=8),
        plot.title=element_text(size=15, hjust = 0.5, face = 'bold'),
        strip.text.x = element_text(size = 12))+
    ylab("values")+
          xlab("Population")

ggsave('C:\\Users\\Yvonne\\Documents\\PHD\\CHP1-FKW\\data\\results\\Pc_Boxplot_Population_PMN_TopImpVars.png', width = 10, height = 5, units = "in", type = "cairo-png")

p


#Plot variables by encounter

w<-ggplot(data_melt_sub,aes(y=value, x = EncounterID)) + 
  facet_wrap(~variable,scales = "free") + 
  geom_boxplot() +
  labs(title="Top Important Variables") +
  theme_bw()+
  theme(axis.text.x=element_text(size=10), 
        axis.title.x=element_text(size=14, face='bold'),
        axis.text.y=element_text(size=12), 
        axis.title.y=element_text(size=14, face='bold'),
         text=element_text(size=8),
        plot.title=element_text(size=15, hjust = 0.5, face = 'bold'),
        strip.text.x = element_text(size = 12))+
    ylab("values")+
          xlab("Acoustic Encounter")

ggsave('C:\\Users\\Yvonne\\Documents\\PHD\\CHP1-FKW\\data\\results\\Pc_Boxplot_Population_PMN_TopImpVars_encounter.png', width = 12, height = 5, units = "in", type = "cairo-png")

w
```


```{r}
      
#BY POPULATION####
  #boxplot
plot_pop<- ggplot(data_melt, aes(y=value, x=population)) +  
  facet_wrap(~variable, scales = "free") +
  geom_boxplot(aes(colour=population)) +
 labs(title="Frequency of the Third Quarter")+ #subtitle="(towed data, incremental random sampling)") + #(includes HARP data, mhi31-34)
  theme_bw() +
  theme(axis.text.x=element_text(size=12),
        axis.text.y=element_text(size=12),
        axis.title.x=element_text(size=14),
        axis.title.y=element_text(size=14),
        plot.title=element_text(size=20, hjust=0.5, face="bold", colour="black", vjust=-1),
        plot.subtitle=element_text(size=16, hjust=0.5, face="italic", color="black"),
        legend.position = "none") +
          ylab("Hertz")+
          xlab("")
          
#saves with better resolution
ggsave('C:\\Users\\Yvonne\\Documents\\PHD\\CHP1-FKW\\data\\results\\Pc_Boxplot_Population_PMN_FREQQUARTER3.png', width = 12, height = 8, units = "in", type = "cairo-png")


#FREQPOSSLOPEMEAN
plot_pop<- ggplot(data_melt, aes(y=value, x=population)) +  
  facet_wrap(~variable, scales = "free") +
  geom_boxplot(aes(colour=population)) +
 labs(title="Mean Positive Slope Frequency")+ #subtitle="(towed data, incremental random sampling)") + #(includes HARP data, mhi31-34)
  theme_bw() +
  theme(axis.text.x=element_text(size=12),
        axis.text.y=element_text(size=12),
        axis.title.x=element_text(size=14),
        axis.title.y=element_text(size=14),
        plot.title=element_text(size=20, hjust=0.5, face="bold", colour="black", vjust=-1),
        plot.subtitle=element_text(size=16, hjust=0.5, face="italic", color="black"),
        legend.position = "none") +
          ylab("Hertz/second")+
          xlab("Population")
          
#saves with better resolution
ggsave('C:\\Users\\Yvonne\\Documents\\PHD\\CHP1-FKW\\data\\results\\Pc_Boxplot_Population_PMN_FREQPOSSLOPEMEAN.png', width = 12, height = 8, units = "in", type = "cairo-png")

  #density plot
plot_popDens<- ggplot(data_melt, aes(x=value, fill=population)) +  
  facet_wrap(~variable, scales = "free") +
  geom_density(alpha=0.3) + #alpha controls shading
labs(title="New Whistle Data by Encounter", subtitle="(no HARP data, incremental random sampling)") +
  theme(plot.background = element_rect(fill = "white"),
        axis.text.x=element_text(size=8),
        axis.text.y=element_text(size=8),
        plot.title=element_text(size=25, hjust=0.5, face="bold", colour="darkblue", vjust=-1),
        plot.subtitle=element_text(size=16, hjust=0.5, face="italic", color="black"))+
          guides(fill=guide_legend(title="Population"))
#saves with better resolution
ggsave('C:\\Users\\Yvonne\\Documents\\PHD\\CHP1-FKW\\data\\results\\Variable Importance\\Pc_DensityPlot_Population_noHARP.png', width = 12, height = 8, units = "in", type = "cairo-png")

```


#Plots with Old Whistle data
```{r warning=FALSE, message=FALSE}
#old data
pcdata<-read.csv('C:\\Users\\Yvonne\\Documents\\PHD\\CHP1-FKW\\data\\2017- 100 New Whistles/BIG ROCCA OLD raw.csv')

#subset for pelagic and mhi
pcdata <- subset(pcdata, pcdata$population != "nwhi")

#with OLD
# pcdata_sub <- pcdata[, c(1,3,9,13,14,20,22,23,30,32,41)]
# 
# #Turn data into long format with melt()
# #Same as new
# data_melt = melt(pcdata_sub, id.vars =c("population", "EncounterID"), measure.vars = c("DURATION", "FREQMEAN", "FREQSTDDEV", "FREQQUARTER1","FREQQUARTER3", "FREQSPREAD", "FREQPOSSLOPEMEAN", "FREQSLOPERATIO", "NUMSWEEPSUPFLAT" ))

# #with OLD
pcdata_sub <- pcdata[, c(1,3,30,31,47)]
#Different than new
data_melt = melt(pcdata_sub, id.vars =c("population", "EncounterID"), measure.vars = c( "FREQPOSSLOPEMEAN", "FREQNEGSLOPEMEAN", "FREQSWEEPFLATPERCENT" ))


#BY ENCOUNTER
plot_enc<- ggplot(data_melt, aes(y=value, x=EncounterID)) +  
  facet_wrap(~variable, scales = "free") +
  geom_boxplot(aes(colour=population)) +
  labs(title="New Whistle Data by Encounter - Top 3", subtitle="(no HARP data, incremental random sampling)") + #(no HARP data, incremental random sampling)
  theme(plot.background = element_rect(fill = "white"),
        axis.text.x=element_text(size=5),
        axis.text.y=element_text(size=8),
        plot.title=element_text(size=25, hjust=0.5, face="bold", colour="darkblue", vjust=-1),
        plot.subtitle=element_text(size=16, hjust=0.5, face="italic", color="black"))+
          guides(fill=guide_legend(title="Population"))
#saves with better resolution
ggsave('C:\\Users\\Yvonne\\Documents\\PHD\\CHP1-FKW\\data\\results\\Variable Importance\\Pc_Boxplot_Encounters_noHARP_top3.png', width = 12, height = 8, units = "in", type = "cairo-png")  


      
#BY POPULATION
  #boxplot
plot_pop<- ggplot(data_melt, aes(y=value, x=population)) +  
  facet_wrap(~variable, scales = "free") +
  geom_boxplot(aes(colour=population)) +
 labs(title="New Whistle Data by Population - Top 3", subtitle="(no HARP data, incremental random sampling)") + #(includes HARP data, mhi31-34)
  theme(plot.background = element_rect(fill = "white"),
        axis.text.x=element_text(size=8),
        axis.text.y=element_text(size=8),
        plot.title=element_text(size=25, hjust=0.5, face="bold", colour="darkblue", vjust=-1),
        plot.subtitle=element_text(size=16, hjust=0.5, face="italic", color="black"))
#saves with better resolution
ggsave('C:\\Users\\Yvonne\\Documents\\PHD\\CHP1-FKW\\data\\results\\Variable Importance\\Pc_Boxplot_Population_noHARP_top3.png', width = 12, height = 8, units = "in", type = "cairo-png")

  #density plot
plot_popDens<- ggplot(data_melt, aes(x=value, fill=population)) +  
  facet_wrap(~variable, scales = "free") +
  geom_density(alpha=0.3) +
labs(title="New Whistle Data by Population", subtitle="(no HARP data, incremental random sampling)") +
  theme(plot.background = element_rect(fill = "white"),
        axis.text.x=element_text(size=8),
        axis.text.y=element_text(size=8),
        plot.title=element_text(size=25, hjust=0.5, face="bold", colour="darkblue", vjust=-1),
        plot.subtitle=element_text(size=16, hjust=0.5, face="italic", color="black"))+
          guides(fill=guide_legend(title="Population"))
#saves with better resolution
ggsave('C:\\Users\\Yvonne\\Documents\\PHD\\CHP1-FKW\\data\\results\\Variable Importance\\Pc_DensityPlot_Population_noHARP.png', width = 12, height = 8, units = "in", type = "cairo-png")

```